const menu = [
  {
    id: 1,
    title: "SAMSUNG LF22T350",
    category: "Samsung",
    price: 14500,
    img: "https://www.startech.com.bd/image/cache/catalog/monitor/samsung/lf22t350fhnxza/lf22t350fhnxza-500x500.jpg",
    desc: `The SAMSUNG monitor featured with 3-sided borderless display brings a clean and modern aesthetic to any working environment. `,
  },
  {
    id: 2,
    title: "Xiaomi Mi FreeSync Curved",
    category: "Xiaomi",
    price: 42000,
    img: "https://www.startech.com.bd/image/cache/catalog/monitor/xiaomi/redmi-34-curved/redmi-34-curved-500x500.jpg",
    desc: `The thin 2 mm bezel not only increases the screen-to-body ratio but also makes the screen edge less distracting is also closer to.`,
  },
  {
    id: 3,
    title: "Dell Curved Gaming",
    category: "Dell",
    price: 30000,
    img: "https://www.startech.com.bd/image/cache/catalog/monitor/dell/s2422hg/s2422hg-24-inch-03-500x500.jpg",
    desc: `Dell S2422HG Gaming Monit. Performance that is high-speed action time thanks to an incredibly fast-moving image response time of.`,
  },
  {
    id: 4,
    title: "Asus Gaming Monitor",
    category: "Asus",
    price: 26300,
    img: "https://www.startech.com.bd/image/cache/catalog/monitor/asus/vp249qgr/vp249qgr-500x500.jpg",
    desc: `The ASUS VP249QGR gaming display is built for victory in the professional gaming arena. With its Full HD IPS  refresh rate with Adaptive-Sync `,
  },
  {
    id: 5,
    title: "GIGABYTE Gaming Monitor",
    category: "Gigabyte",
    price: 28999,
    img: "https://www.startech.com.bd/image/cache/catalog/monitor/gigabyte/g27f/g27f-010-500x500.jpg",
    desc: `The latest GIGABYTE gaming monitors offer the ultimate specifications and quality, users can truly enjoy upscale performance without the need for extravagance.`,
  },
  {
    id: 6,
    title: "Dell IPS Monitor",
    category: "Dell",
    price: 19000,
    img: "https://www.startech.com.bd/image/cache/catalog/monitor/dell/p2722h/p2722h-01-500x500.jpg",
    desc: `This monitor comes with DisplayPort, HDMI, VGA, and 4x SuperSpeed USB 5Gbps ports connectivity. It gives you more room for connectivity.`,
  },
  {
    id: 7,
    title: "ASUS TUF Gaming",
    category: "Asus",
    price: 15000,
    img: "https://www.startech.com.bd/image/cache/catalog/monitor/asus/vg279qm/vg279qm-500x500.jpg",
    desc: `Astonishing overclockable 280Hz refresh rate means the display is almost twice as fast as conventional 144 Hz monitors. `,
  },
  {
    id: 8,
    title: "Xiaomi Mi 1C",
    category: "Xiaomi",
    price: 12000,
    img: "https://www.startech.com.bd/image/cache/catalog/monitor/xiaomi/mi-1c/mi-1c-1-500x500.jpeg",
    desc: `This monitor is also featured with stands out in terms of connectivity, these are VGA and HDMI connectivity. Here, Low-intensity blue light also available.`,
  },
  {
    id: 9,
    title: "Samsung Odyssey",
    category: "Samsung",
    price: 175000,
    img: "https://www.startech.com.bd/image/cache/catalog/monitor/samsung/c49g95tssw/c49g95tssw-1-500x500.jpg",
    desc: `This gaming monitor's display is featured with Max 240Hz Frame Rate.Gaming Monitor has 03 yeas warranty.`,
  },
  {
    id: 10,
    title: "Samsung Odyssey",
    category: "Gigabyte",
    price: 17000,
    img: "https://www.startech.com.bd/image/cache/catalog/Monitor/GIGABYTE/m27q-p/gigabyte-m27q-p-27inch-monitor-01-500x500.jpg",
    desc: `Bring fast-paced and flexible performance to your gaming setup with the M27Q P 27" 1440p HDR 165 Hz Gaming Monitor from Gigabyte.`,
  },
];
export default menu;
